# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOkzAfI7XGTX9Di4mNyPxk_Y5onpwYCA
"""

# extended_compare_nodes_pairs.py
import numpy as np
import networkx as nx
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# ---------- Networks ----------
def create_double_star_13():
    G = nx.Graph()
    G.add_nodes_from(range(1,14))
    G.add_edge(1,2)
    for i in range(3,8): G.add_edge(2,i)
    G.add_edge(1,8)
    for i in range(9,14): G.add_edge(8,i)
    return G

def create_double_star_15():
    G = nx.Graph()
    G.add_nodes_from(range(1,16))
    G.add_edge(1,2)
    for i in range(3,8): G.add_edge(2,i)
    G.add_edge(1,8)
    for i in range(9,16): G.add_edge(8,i)
    return G

# ---------- Centrality calculations ----------
def calculate_single_node_index(G):
    nodelist = sorted(G.nodes())
    L = nx.laplacian_matrix(G, nodelist=nodelist).toarray()
    eigenvalues, eigenvectors = np.linalg.eigh(L)
    fiedler_vector = eigenvectors[:, 1]  # 2nd smallest
    indices = {}
    for i in nodelist:
        r_i = 0
        xi = fiedler_vector[i - 1]
        for neighbor in G.neighbors(i):
            xj = fiedler_vector[neighbor - 1]
            r_i += abs(xi - xj)
        indices[i] = r_i
    return indices, fiedler_vector

def calculate_node_pair_matrix(G, single_node_indices, fiedler_vector):
    nodelist = sorted(G.nodes())
    num_nodes = len(nodelist)
    R2_matrix = np.zeros((num_nodes, num_nodes))
    for j_idx, node_j in enumerate(nodelist):
        for k_idx, node_k in enumerate(nodelist):
            if j_idx >= k_idx: continue
            R_j = single_node_indices[node_j]
            R_k = single_node_indices[node_k]
            intersection_count = 1 if G.has_edge(node_j, node_k) else 0
            x_j = fiedler_vector[j_idx]
            x_k = fiedler_vector[k_idx]
            correction_term = intersection_count * abs(x_j - x_k)
            R_jk = R_j + R_k - correction_term
            R2_matrix[j_idx, k_idx] = R_jk
    return R2_matrix

# ---------- Chua dynamics ----------
def chua_f(x):
    p,q,r = x
    gamma1, gamma2, gamma3, gamma4 = 10.0, 18.0, -4.0/3.0, -3.0/4.0
    g_p = gamma4 * p + 0.5 * (gamma3 - gamma4) * (abs(p+1) - abs(p-1))
    return np.array([-gamma1 * (p - q + g_p), p - q + r, -gamma2 * q])

def make_coupled_chua_with_adaptive_edges(G, control_node_set, c=2.0, alpha=1.0):
    nodes = sorted(G.nodes())
    N = len(nodes)
    node_to_idx = {node: i for i,node in enumerate(nodes)}
    edges = sorted([(min(u,v), max(u,v)) for u,v in G.edges()])
    M = len(edges)

    adaptive_mask = np.zeros(M)
    for ei,(u,v) in enumerate(edges):
        if (u in control_node_set) or (v in control_node_set):
            adaptive_mask[ei] = 1

    H = np.eye(3)

    def ode(t, y):
        x_flat = y[:N*3]
        w = y[N*3:]
        X = x_flat.reshape((N,3))

        # weighted adjacency
        A = np.zeros((N,N))
        for k,(u,v) in enumerate(edges):
            i,j = node_to_idx[u], node_to_idx[v]
            A[i,j] = w[k]; A[j,i] = w[k]
        D = np.diag(A.sum(axis=1))
        L = D - A

        dx = np.zeros_like(X)
        for i in range(N):
            dx[i] = chua_f(X[i])
            for j in range(N):
                if L[i,j] != 0:
                    dx[i] -= c * L[i,j] * (H @ X[j])

        dw = np.zeros(M)
        for k,(u,v) in enumerate(edges):
            if adaptive_mask[k]:
                i,j = node_to_idx[u], node_to_idx[v]
                diff = X[i] - X[j]
                dw[k] = alpha * float(diff @ (H @ diff))
        return np.concatenate([dx.flatten(), dw])

    return ode, nodes, edges

def run_scenario(G, control_nodes, t_span=(0,12), t_eval=None, c=2.0, alpha=1.0, seed=42):
    if t_eval is None: t_eval = np.linspace(t_span[0], t_span[1], 600)
    ode_fun, nodes, edges = make_coupled_chua_with_adaptive_edges(G, control_nodes, c, alpha)
    N, M = len(nodes), len(edges)
    rng = np.random.RandomState(seed)
    x0 = (rng.rand(N*3)-0.5)*10
    w0 = np.ones(M)
    y0 = np.concatenate([x0, w0])
    sol = solve_ivp(fun=ode_fun, t_span=t_span, y0=y0, t_eval=t_eval, rtol=1e-6, atol=1e-9)
    return sol, nodes

def sync_errors_from_solution(sol, N):
    x_traj = sol.y[:N*3,:].reshape((N,3,-1))
    T = x_traj.shape[2]
    errors = np.zeros((N,T))
    for t in range(T):
        avg = x_traj[:,:,t].mean(axis=0)
        for i in range(N):
            errors[i,t] = np.linalg.norm(x_traj[i,:,t]-avg)
    return errors

def time_to_sync(errors, t_eval, tol=1e-3):
    max_err = errors.max(axis=0)
    below = np.where(max_err < tol)[0]
    return t_eval[below[0]] if len(below)>0 else np.inf

# ---------- Main ----------
if __name__=="__main__":
    networks = {
        "Paper Symmetric (13 nodes)": create_double_star_13(),
        "Asymmetric (15 nodes)": create_double_star_15()
    }
    results = []
    for name,G in networks.items():
        print(f"\n--- {name} ---")
        single_indices,fiedler = calculate_single_node_index(G)
        R2 = calculate_node_pair_matrix(G, single_indices, fiedler)

        # most important node
        node_imp = max(single_indices.items(), key=lambda x:x[1])
        imp_node, imp_val = node_imp
        print(f"Most important node: {imp_node} (R={imp_val:.4f})")

        # most important pair
        idx = np.unravel_index(np.argmax(R2), R2.shape)
        nodelist = sorted(G.nodes())
        imp_pair = (nodelist[idx[0]], nodelist[idx[1]])
        imp_pair_val = R2[idx]
        print(f"Most important pair: {imp_pair} (R={imp_pair_val:.4f})")

        # run simulations
        t_eval = np.linspace(0,12,600)
        sol_node,_ = run_scenario(G,[imp_node],t_eval=t_eval)
        err_node = sync_errors_from_solution(sol_node,len(G))
        t_sync_node = time_to_sync(err_node,t_eval)

        sol_pair,_ = run_scenario(G,list(imp_pair),t_eval=t_eval)
        err_pair = sync_errors_from_solution(sol_pair,len(G))
        t_sync_pair = time_to_sync(err_pair,t_eval)

        print(f"Sync time (node {imp_node}): {t_sync_node:.2f}")
        print(f"Sync time (pair {imp_pair}): {t_sync_pair:.2f}")

        results.append([name, imp_node, imp_val, t_sync_node, imp_pair, imp_pair_val, t_sync_pair])

    # make summary table
    import pandas as pd
    df = pd.DataFrame(results, columns=["Network","Most Imp Node","R(node)","SyncTime(node)",
                                        "Most Imp Pair","R(pair)","SyncTime(pair)"])
    print("\nSummary:")
    print(df.to_string(index=False))

    G = create_double_star_13()
    pos = nx.spring_layout(G, seed=42)

    # Draw initial network
    nx.draw(G, pos, with_labels=True, node_size=1000, node_color="skyblue", edge_color="gray")
    plt.title("Double-Star Network (Initial)", fontsize=14)
    plt.show()