# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOkzAfI7XGTX9Di4mNyPxk_Y5onpwYCA
"""

# extended_compare_nodes_pairs.py
import numpy as np
import networkx as nx
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# ---------- Networks ----------
def create_double_star_13():
    G = nx.Graph()
    G.add_nodes_from(range(1,14))
    G.add_edge(1,2)
    for i in range(3,8): G.add_edge(2,i)
    G.add_edge(1,8)
    for i in range(9,14): G.add_edge(8,i)
    return G

def create_double_star_15():
    G = nx.Graph()
    G.add_nodes_from(range(1,16))
    G.add_edge(1,2)
    for i in range(3,8): G.add_edge(2,i)
    G.add_edge(1,8)
    for i in range(9,16): G.add_edge(8,i)
    return G

# ---------- Centrality calculations ----------
def calculate_single_node_index(G):
    nodelist = sorted(G.nodes())
    L = nx.laplacian_matrix(G, nodelist=nodelist).toarray()
    eigenvalues, eigenvectors = np.linalg.eigh(L)
    fiedler_vector = eigenvectors[:, 1]  # 2nd smallest
    indices = {}
    for i in nodelist:
        r_i = 0
        xi = fiedler_vector[i - 1]
        for neighbor in G.neighbors(i):
            xj = fiedler_vector[neighbor - 1]
            r_i += abs(xi - xj)
        indices[i] = r_i
    return indices, fiedler_vector

def calculate_node_pair_matrix(G, single_node_indices, fiedler_vector):
    nodelist = sorted(G.nodes())
    num_nodes = len(nodelist)
    R2_matrix = np.zeros((num_nodes, num_nodes))
    for j_idx, node_j in enumerate(nodelist):
        for k_idx, node_k in enumerate(nodelist):
            if j_idx >= k_idx: continue
            R_j = single_node_indices[node_j]
            R_k = single_node_indices[node_k]
            intersection_count = 1 if G.has_edge(node_j, node_k) else 0
            x_j = fiedler_vector[j_idx]
            x_k = fiedler_vector[k_idx]
            correction_term = intersection_count * abs(x_j - x_k)
            R_jk = R_j + R_k - correction_term
            R2_matrix[j_idx, k_idx] = R_jk
    return R2_matrix

# ---------- Chua dynamics ----------
def chua_f(x):
    p,q,r = x
    gamma1, gamma2, gamma3, gamma4 = 10.0, 18.0, -4.0/3.0, -3.0/4.0
    g_p = gamma4 * p + 0.5 * (gamma3 - gamma4) * (abs(p+1) - abs(p-1))
    return np.array([-gamma1 * (p - q + g_p), p - q + r, -gamma2 * q])

def make_coupled_chua_with_adaptive_edges(G, control_node_set, c=2.0, alpha=1.0):
    nodes = sorted(G.nodes())
    N = len(nodes)
    node_to_idx = {node: i for i,node in enumerate(nodes)}
    edges = sorted([(min(u,v), max(u,v)) for u,v in G.edges()])
    M = len(edges)

    adaptive_mask = np.zeros(M)
    for ei,(u,v) in enumerate(edges):
        if (u in control_node_set) or (v in control_node_set):
            adaptive_mask[ei] = 1

    H = np.eye(3)

    def ode(t, y):
        x_flat = y[:N*3]
        w = y[N*3:]
        X = x_flat.reshape((N,3))

        # weighted adjacency
        A = np.zeros((N,N))
        for k,(u,v) in enumerate(edges):
            i,j = node_to_idx[u], node_to_idx[v]
            A[i,j] = w[k]; A[j,i] = w[k]
        D = np.diag(A.sum(axis=1))
        L = D - A

        dx = np.zeros_like(X)
        for i in range(N):
            dx[i] = chua_f(X[i])
            for j in range(N):
                if L[i,j] != 0:
                    dx[i] -= c * L[i,j] * (H @ X[j])

        dw = np.zeros(M)
        for k,(u,v) in enumerate(edges):
            if adaptive_mask[k]:
                i,j = node_to_idx[u], node_to_idx[v]
                diff = X[i] - X[j]
                dw[k] = alpha * float(diff @ (H @ diff))
        return np.concatenate([dx.flatten(), dw])

    return ode, nodes, edges

def run_scenario(G, control_nodes, t_span=(0,12), t_eval=None, c=2.0, alpha=1.0, seed=42):
    if t_eval is None: t_eval = np.linspace(t_span[0], t_span[1], 600)
    ode_fun, nodes, edges = make_coupled_chua_with_adaptive_edges(G, control_nodes, c, alpha)
    N, M = len(nodes), len(edges)
    rng = np.random.RandomState(seed)
    x0 = (rng.rand(N*3)-0.5)*10
    w0 = np.ones(M)
    y0 = np.concatenate([x0, w0])
    sol = solve_ivp(fun=ode_fun, t_span=t_span, y0=y0, t_eval=t_eval, rtol=1e-6, atol=1e-9)
    return sol, nodes

def sync_errors_from_solution(sol, N):
    x_traj = sol.y[:N*3,:].reshape((N,3,-1))
    T = x_traj.shape[2]
    errors = np.zeros((N,T))
    for t in range(T):
        avg = x_traj[:,:,t].mean(axis=0)
        for i in range(N):
            errors[i,t] = np.linalg.norm(x_traj[i,:,t]-avg)
    return errors

def time_to_sync(errors, t_eval, tol=1e-3):
    max_err = errors.max(axis=0)
    below = np.where(max_err < tol)[0]
    return t_eval[below[0]] if len(below)>0 else np.inf

def calculate_single_node_index(G):
    nodelist = sorted(G.nodes())
    L = nx.laplacian_matrix(G, nodelist=nodelist).toarray()
    eigenvalues, eigenvectors = np.linalg.eigh(L)
    fiedler_vector = eigenvectors[:, 1]  # 2nd smallest
    indices = {}
    for i in nodelist:
        r_i = 0
        xi = fiedler_vector[i - 1]
        for neighbor in G.neighbors(i):
            xj = fiedler_vector[neighbor - 1]
            r_i += abs(xi - xj)
        indices[i] = r_i
    return indices, fiedler_vector

def calculate_node_pair_matrix(G, single_node_indices, fiedler_vector):
    nodelist = sorted(G.nodes())
    num_nodes = len(nodelist)
    R2_matrix = np.zeros((num_nodes, num_nodes))
    for j_idx, node_j in enumerate(nodelist):
        for k_idx, node_k in enumerate(nodelist):
            if j_idx >= k_idx: continue
            R_j = single_node_indices[node_j]
            R_k = single_node_indices[node_k]
            intersection_count = 1 if G.has_edge(node_j, node_k) else 0
            x_j = fiedler_vector[j_idx]
            x_k = fiedler_vector[k_idx]
            correction_term = intersection_count * abs(x_j - x_k)
            R_jk = R_j + R_k - correction_term
            R2_matrix[j_idx, k_idx] = R_jk
    return R2_matrix

def add_centrality_attributes_to_graph(G, single_node_indices, fiedler_vector, R2_matrix, include_virtual_edges=True):
    """Add centrality metrics as node and edge attributes"""
    nodelist = sorted(G.nodes())
    
    # Add node attributes
    for i, node in enumerate(nodelist):
        G.nodes[node]['fiedler_value'] = float(fiedler_vector[i])
        G.nodes[node]['R_value'] = float(single_node_indices[node])
        G.nodes[node]['degree'] = G.degree(node)
        G.nodes[node]['node_id'] = node
        
        # Add normalized versions for better visualization in Gephi
        G.nodes[node]['fiedler_normalized'] = float(fiedler_vector[i])
        G.nodes[node]['R_normalized'] = float(single_node_indices[node])
    
    # Store original edges for marking
    original_edges = set(G.edges())
    
    # Add virtual edges for all non-connected pairs if requested
    if include_virtual_edges:
        for i in range(len(nodelist)):
            for j in range(i+1, len(nodelist)):
                node_u, node_v = nodelist[i], nodelist[j]
                if not G.has_edge(node_u, node_v):
                    G.add_edge(node_u, node_v)
    
    # Add edge attributes with R² values for ALL edges (original + virtual)
    for edge in G.edges():
        node_u, node_v = edge
        u_idx = nodelist.index(node_u)
        v_idx = nodelist.index(node_v)
        
        # Get R² value for this pair
        if u_idx < v_idx:
            r2_value = R2_matrix[u_idx, v_idx]
        else:
            r2_value = R2_matrix[v_idx, u_idx]
        
        G.edges[edge]['R2_value'] = float(r2_value)
        
        # Mark edge type
        if edge in original_edges or (node_v, node_u) in original_edges:
            G.edges[edge]['edge_type'] = 'original'
            G.edges[edge]['weight'] = 1.0  # Original edges have weight 1
        else:
            G.edges[edge]['edge_type'] = 'virtual'
            G.edges[edge]['weight'] = 0.1  # Virtual edges have lower weight
        
        # Add individual R values for the connected nodes
        G.edges[edge]['R_u'] = float(single_node_indices[node_u])
        G.edges[edge]['R_v'] = float(single_node_indices[node_v])
        
        # Add Fiedler difference
        u_fiedler = fiedler_vector[u_idx]
        v_fiedler = fiedler_vector[v_idx]
        G.edges[edge]['fiedler_diff'] = float(abs(u_fiedler - v_fiedler))
        
        # Add sum of individual R values for comparison
        G.edges[edge]['R_sum'] = float(single_node_indices[node_u] + single_node_indices[node_v])

def export_enhanced_gexf(network_name, G):
    """Export graph with all centrality attributes to GEXF"""
    # Calculate centrality metrics
    single_indices, fiedler = calculate_single_node_index(G)
    R2_matrix = calculate_node_pair_matrix(G, single_indices, fiedler)
    
    # Add attributes to graph
    add_centrality_attributes_to_graph(G, single_indices, fiedler, R2_matrix)
    
    # Normalize values for better visualization (0-1 range)
    all_r_values = list(single_indices.values())
    all_fiedler_values = list(fiedler)
    
    r_min, r_max = min(all_r_values), max(all_r_values)
    f_min, f_max = min(all_fiedler_values), max(all_fiedler_values)
    
    for node in G.nodes():
        if r_max != r_min:
            G.nodes[node]['R_normalized'] = (single_indices[node] - r_min) / (r_max - r_min)
        if f_max != f_min:
            node_idx = sorted(G.nodes()).index(node)
            G.nodes[node]['fiedler_normalized'] = (fiedler[node_idx] - f_min) / (f_max - f_min)
    
    # Export to GEXF
    filename = f"{network_name.lower().replace(' ', '_').replace('(', '').replace(')', '')}.gexf"
    nx.write_gexf(G, filename)
    print(f"Enhanced GEXF exported to: {filename}")
    
    # Print summary of attributes added
    print(f"Node attributes added: {list(G.nodes(data=True))[0][1].keys()}")
    print(f"Edge attributes added: {list(G.edges(data=True))[0][2].keys()}")
    
    return filename

# ---------- Main ----------
if __name__=="__main__":
    networks = {
        "Paper Symmetric (13 nodes)": create_double_star_13(),
        "Asymmetric (15 nodes)": create_double_star_15()
    }
    results = []
    for name,G in networks.items():
        print(f"\n--- {name} ---")
        single_indices,fiedler = calculate_single_node_index(G)
        R2 = calculate_node_pair_matrix(G, single_indices, fiedler)

        # most important node
        node_imp = max(single_indices.items(), key=lambda x:x[1])
        imp_node, imp_val = node_imp
        print(f"Most important node: {imp_node} (R={imp_val:.4f})")

        # most important pair
        idx = np.unravel_index(np.argmax(R2), R2.shape)
        nodelist = sorted(G.nodes())
        imp_pair = (nodelist[idx[0]], nodelist[idx[1]])
        imp_pair_val = R2[idx]
        print(f"Most important pair: {imp_pair} (R={imp_pair_val:.4f})")

        # run simulations
        t_eval = np.linspace(0,12,600)
        sol_node,_ = run_scenario(G,[imp_node],t_eval=t_eval)
        err_node = sync_errors_from_solution(sol_node,len(G))
        t_sync_node = time_to_sync(err_node,t_eval)

        sol_pair,_ = run_scenario(G,list(imp_pair),t_eval=t_eval)
        err_pair = sync_errors_from_solution(sol_pair,len(G))
        t_sync_pair = time_to_sync(err_pair,t_eval)

        print(f"Sync time (node {imp_node}): {t_sync_node:.2f}")
        print(f"Sync time (pair {imp_pair}): {t_sync_pair:.2f}")

        results.append([name, imp_node, imp_val, t_sync_node, imp_pair, imp_pair_val, t_sync_pair])

    # make summary table
    import pandas as pd
    df = pd.DataFrame(results, columns=["Network","Most Imp Node","R(node)","SyncTime(node)",
                                        "Most Imp Pair","R(pair)","SyncTime(pair)"])
    print("\nSummary:")
    print(df.to_string(index=False))

    # # G = create_double_star_13()
    # pos = nx.spring_layout(G, seed=42)

    # # Draw initial network
    # nx.draw(G, pos, with_labels=True, node_size=1000, node_color="skyblue", edge_color="gray")
    # plt.title("Double-Star Network", fontsize=14)
    # plt.show()

    export_enhanced_gexf("Asymmetric (15 nodes)", G)
    export_enhanced_gexf("Paper Symmetric (13 nodes)", G)

    # nx.write_gexf(G, "double_star_network.gexf")